const USER_STATE_CHANGE = "USER_STATE_CHANGE"
const CLEAR_DATA = "CLEAR_DATA"
const RESET_STATE = 'RESET_STATE'
const UPDATE_TITLE = "UPDATE_TITLE"

export {
  USER_STATE_CHANGE,
  CLEAR_DATA,
  RESET_STATE,
  UPDATE_TITLE
}
