const USER_STATE_CHANGE = "USER_STATE_CHANGE"
const CLEAR_DATA = "CLEAR_DATA"
const SEND_VERIFICATION_EMAIL_SUCCESS = "SEND_VERIFICATION_EMAIL_SUCCESS"
const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS"
const UPDATE_TITLE = "UPDATE_TITLE"

export {
  USER_STATE_CHANGE,
  CLEAR_DATA,
  SEND_VERIFICATION_EMAIL_SUCCESS,
  VERIFY_EMAIL_SUCCESS,
  UPDATE_TITLE
}
